export const GET_ITEMS='GET_ITEMS';
export const ADD_ITEM='ADD_ITEM';
export const DELETE_ITEM='DELETE_ITEM';
export const LOADING='LOADING';
export const GET_ERROR='GET_ERROR';
export const CLEAR_ERROR='CLEAR_ERROR';

export const USER_LOADING='USER_LOADING';
export const USER_LODED='USER_LODED';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const REGISTER_FAIL='REGISTER_FAIL';
export const AUTH_ERROR='AUTH_ERROR';
